### ISSUE TITLE
Downloads literally all the files

### ISSUE THREAD

**Issue by dummifiedme** [djsudduth/keep-it-markdown#10]
--all command downloads even the Bin and Archived files!!

How can I then download only the ones that are in the main folder?

Also, how can I specifically capture those with a particular label. (with or without hastag???)

**Comment by djsudduth** [comment]
That is a bug - trash ad archived should be ignored.  To search/export label - use the # sign like #Mylabel or #My Label.  Also, search is case sensitive and do not use quotes!

**Comment by dummifiedme** [comment]
Sure, thanks.

**Comment by djsudduth** [comment]
Added fix in 0.3.0 - archive notes are ignored unless specifically exported with the new -a flag
