### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by lucky-d-ui** [djsudduth/keep-it-markdown#13]
I have a new problem

I am Russian 😅 
Cyrillic text is not exported. Transfers as ���.

Also KIM does not support labels and 'my search term' in Russian. But this is not so important anymore.

can we make it multilingual?

**Comment by djsudduth** [comment]
I'll take a look - right now KIM is not Unicode compliant.

**Comment by djsudduth** [comment]
Looking at the code this is both an enhancement and a bug!  @lucky-d-ui I will have it fixed in version 0.3.1.
В следующей версии исправлю! Хорошего дня!

**Comment by djsudduth** [comment]
@lucky-d-ui  foreign language is now supported.  I tested some Russian using Google Translate and it seemed to work - would like you to test it if possible.  Thanks!

**Comment by lucky-d-ui** [comment]
Great!
Thank you very much 👏
It works
