### ISSUE TITLE
 The script doesnt work

### ISSUE THREAD

**Issue by tcikovsky** [djsudduth/keep-it-markdown#28]
I don't understand what google username means. Is it just the name of the google account. I also saw a version mentioning something called google id? What is it? I tried my google name (my actual name and the name of the account) but it returns an exception. I don't know if the name is wrong but I need to know what it is to figure out what the problem is either way. Could you please elaborate on "username"? What is it and where do I find it.

**Comment by tcikovsky** [comment]
my dumb ass just has a broken git bash. i am so sorry for the inconvenience.

**Comment by djsudduth** [comment]
@tcikovsky - the google username is the account id you use to log into google. It is typically an email account id if you are not using other Google services like 'myname@yahoo.com', or, if you have a gmail account that is 'myname@gmail.com' you can use that. If you have gmail you can also just enter 'myname' without the @gmail extension - that works as well.

**Comment by tcikovsky** [comment]
okay yeah that helped, also I don't want to order you in any way or anything but that is rather confusing, I think it would really help to add that to the readme. again not really my place to speak, just some feedback

**Comment by djsudduth** [comment]
@tcikovsky  - thanks for the feedback!! No problem and hope it works for you. Just an FYI - if you have issues with converting checkboxes in 0.4.0, just download the kim.py in the dev branch for the fix. 0.4.1 is just about ready.
