### ISSUE TITLE
requirements.txt missing

### ISSUE THREAD

**Issue by filipgoc** [djsudduth/keep-it-markdown#3]
Hi, I noticed the latest release is missing `requirements.txt`. It's just not there. 
Presumably this should be the same as in 0.1.0, but I don't know. 
Cheers!

**Comment by djsudduth** [comment]
Ah - sorry - will fix it. It is the same yes.

**Comment by djsudduth** [comment]
Fixed in 0.2.1 - requirements file added back in.
