### ISSUE TITLE
App password - workaround for login issue

### ISSUE THREAD

**Issue by BatmanAoD** [djsudduth/keep-it-markdown#33]
I was unable to log in using the instructions in the README, but creating an app password worked with no issues. Here are the app password instructions: https://support.google.com/accounts/answer/185833

I don't know exactly what the problem was, but I suspect it may be that my account has 2FA configured. I am on a Windows machine, but my `gkeepapi` version is 0.13.6 (which should have the fix mentioned in #4). The other possibility is that it didn't work because Firefox is my default browser (I don't even have Chrome installed).

I think it would be good to mention this as a viable workaround in the README.

**Comment by djsudduth** [comment]
This is addressed in #42 - add any comments there.
