### ISSUE TITLE
--all option fails to export all notes

### ISSUE THREAD

**Issue by snokec** [djsudduth/keep-it-markdown#36]
Using the `--all` option, `kim.py` reports 501 exported notes. However only ~257 notes are exported. Using Google Takeout, I confirmed I do have a total of `501` notes - so `kim.py` is reporting the correct number of source notes but not actually converting all of them. The script does not appear to be crashing.

**Comment by djsudduth** [comment]
Thanks for letting me know @snokec - what version were you using, Python version, OS and if some of your notes do not have titles (just a hunch).

**Comment by snokec** [comment]
kim.py `0.4.3`
python `3.8.10`
MacOS `10.15.7`

I do have some notes without titles - but not enough to make up the difference - and it looks like they were converted successfully with dates as titles. However I have many notes in Keep with duplicate titles, and it appears only one note per title was converted. I'm not using any script options except `--all`.

I may try to compare my takeout export to the converted notes and see if there are any other patterns.

**Comment by devidw** [comment]
@snokec Are some of the notes you are missing in the archive?

> All queries to convert ignore notes in archive and trash.

 You can have a look into the [archive notes section](https://github.com/djsudduth/keep-it-markdown/#archive-notes) in the `README.md` for how to export those.

**Comment by djsudduth** [comment]
@snokec @devidw  - good question about the archived notes. However, there does seem to be a counting issue with the `--all` switch. I'm still getting all notes exported I believe, but the count number on the screen seems off.  I'll check into that.

@snokec can you confirm the archive question please?  Thanks!

**Comment by djsudduth** [comment]
@devidw - your very good point on archived notes gave me a thought on the count issue - when I walked over to get my coffee I realized that the count with `--all` is most likely counting both archive and trash notes even though they are not converted. I will test that.

cc @snokec

**Comment by snokec** [comment]
I did some digging:

- Google Takeout for Keep produces 501 note files
- KIM reports 501 notes converted when using `--all` option

So those numbers match. I agree that the `--all` count seems to be counting archived notes (not converted with `--all`) as well as non-archived notes.

If I do a quick scan of my Keep notes, rounding numbers for arguments sake, I have ~260 non-archived notes and ~240 archived notes. If I do an exact count, which I'm not planning on doing, the real numbers probably add up to 501.

However, when I use KIM to convert **_archived_** notes using the appropriate option, I'm only getting ~11 notes converted.

So, approximating:
- non-archived total = 260, converted = 257 (I'm rounding so these numbers may actually match)
- archived total = 240, converted = 11

I'm not clear on why so few archived notes are being converted. I took a quick scan through my archived notes in Keep and noticed that many were originally created as Keep reminders - they have a short title and no body. Maybe this is important.

I hope this helps - let me know if there's any other info I can provide.

**Comment by djsudduth** [comment]
@snokec - thank you for doing the scan! I think you've uncovered 2 issues - 1) archive notes being counted even though they are ignored when not using the `-a` switch, and 2) reminders might be ignored completely.  I will take a look!

**Comment by snokec** [comment]
@djsudduth one addition: though many of my archived notes were originally created as reminders (title but no body/content) - they no longer have reminder date/times associated with them. They therefore appear in Keep as regular notes with a title but no body/content (they do **_not_** appear when clicking from the _Notes_ filter to the _Reminders_ filter in the Keep UI).

Not sure if Keep/Keep API stores or returns reminder notes differently than "regular" notes - or if Keep/KeepAPI still considers reminder notes as "reminders" if the date/time portion has been removed from the note, but wanted to point this out.

**Comment by djsudduth** [comment]
@snokec - confirmed bug #1 - the count is all notes including archive and trash (but only non-archived/trash notes being converted)

But, for #2 I can't duplicate. I see what you're seeing - the reminders disappear in some cases. I tried putting reminders with short titles and no body in my main notes and moved some to archive and trash and back - they still get converted from archive. Is there something else in your reminder notes that is different?   Titles, or labels - anything else?

**Comment by djsudduth** [comment]
@snokec  - just a thought - try this command if you haven't yet -> `kim.py -a -b --all` and see if the reminder notes still are ignored.

**Comment by djsudduth** [comment]
@snokec if you want to fix the counting issue manually - add this just after line 304 in kim.py  
      `else:
            ccnt = 0`

**Comment by djsudduth** [comment]
@snokec if you want to fix the counting bug manually for now - you need to add 2 lines after line 304 in kim.py
     else:  
            ccnt = 0  
note that the indents must match

**Comment by snokec** [comment]
> But, for 2 I can't duplicate. I see what you're seeing - the reminders disappear in some cases. I tried putting reminders with short titles and no body in my main notes and moved some to archive and trash and back - they still get converted from archive. Is there something else in your reminder notes that is different? Titles, or labels - anything else?

* Not that I can see - most of them have no dates, no labels/tags, etc. Just a title with no body
* Also out of ~240 archived notes, less than half are old reminders, so there are lots of other archived notes that aren't converting with the `-a` option

> just a thought - try this command if you haven't yet -> kim.py -a -b --all and see if the reminder notes still are ignored

* Progress! This successfully converted 244 archived notes, which is probably all of them

**Comment by djsudduth** [comment]
@snokec - so if the `kim.py -a -b --all` worked for you with archived notes, what command and switch were you running? Just the `kim.py -a`  and then typed `--all` in the prompt?

**Comment by snokec** [comment]
@djsudduth
Your question made me realize I was probably not using the `-a` option for archived notes correctly.
If I do `python3 kim.py -a` then `--all` at the prompt - all of my archived notes are converted.
If I do `python3 kim.py` then `--all` at the prompt - all of my non-archived notes are converted.
These two together seem to catch everything.
I don't remember exactly what I was doing before but I was likely getting confused that some options (`-a`) should be used when initially executing `kim.py`, while others (`--all`) should be used at the prompt _after_ executing `kim.py`.
Apologies for any churn I caused.
