### ISSUE TITLE
How I solved my keyring sign-in issue 

### ISSUE THREAD

**Issue by ichmoimeyo** [djsudduth/keep-it-markdown#37]
I used to have sign in problems ...
I was able to solve it with ...

pip3 install --upgrade keyrings.alt    **---OR---**    pip install --upgrade keyrings.alt

[... from [stackoverflow](https://stackoverflow.com/questions/53164278/missing-dependencies-causing-keyring-error-when-opening-spyder3-on-ubuntu18) ]

This way I just enter the pin# I chose and haven't had any problems since.

/////////////////////
Enter your Google account username: xdxdxd
Please enter password for encrypted keyring: zzzz
You've succesfully logged into Google Keep using local keyring access token!

Enter a keyword search, label search or '--all' to convert Keep notes to md or '--x' to exit: 
/////////////////////

... hope that helps somebody else.

/////////////////////////////////////////

https://www.pythonpool.com/pip-vs-pip3/
>python --version
Python 3.8.12
>which pip
/opt/virtualenvs/python3/bin/pip
>which pip3
/opt/virtualenvs/python3/bin/pip3

**Comment by djsudduth** [comment]
@ichmoimeyo thank you!

**Comment by djsudduth** [comment]
Changes to gpsoauth module deprecated these issues. No longer valid.
