### ISSUE TITLE
cannot log in

### ISSUE THREAD

**Issue by filipgoc** [djsudduth/keep-it-markdown#4]
Hi, I was not able to make this work. Could not log in.

I tried the captcha in browser as in readme.md and I also tried a generated google app password (as I use multi-authentification), but no luck.

I am not sure how to troubleshoot or if that is possible.

**Comment by djsudduth** [comment]
Ok - thanks for letting me know. What OS are you running and Python version?  The Keep library used has had this issue for some. There is an OAuth addition that may help.

**Comment by djsudduth** [comment]
One possible suggestion - be sure you are using Chrome and you're logged into your Google account on the Google homepage in Chrome before login testing. Then try keep-test.py to see if it works. Be sure to use your full Google ID and have typed it in correctly in keep-test.py

**Comment by djsudduth** [comment]
Also, looking a the 'unofficial' keep API (gkeepapi ) issues list - they noted in that something in the TLS security changed in Python and that a re-install of 3.7+ seemed to fix the login issue. Not sure you want to go that far.

**Comment by lucky-d-ui** [comment]
I want to go that far! 😅

**Comment by lucky-d-ui** [comment]
Is it normal that I can't see the password when I enter it?

**Comment by djsudduth** [comment]
@lucky-d-ui - yes, right now the pw input does not show dots as characters - that's on the backlog.  Just type in your pw and press enter.

**Comment by djsudduth** [comment]
Note that I just ran into the problem only on Windows - no issues on Linux and Mac.

**Comment by djsudduth** [comment]
@filipgoc - some progress on bad logins.  There seems to have been a problem with one of the Python libraries that Google Keep API uses.  If you run a command line and type -> pip list (or pip3 list depending if you have both Python 2 and 3 installed) look to see what version of requests is being used.  It should be 2.23.0. If it is 2.24.x or higher type this:

pip install requests==2.23.0

**Comment by lucky-d-ui** [comment]
20.2.3 used

**Comment by djsudduth** [comment]
@lucky-d-ui not sure what you mean. Did you try the `pip install` And did it work? The version number you mentioned isn’t correct.

**Comment by lucky-d-ui** [comment]
I don't know what problem(
I took a new computer - everything worked!

**Comment by lucky-d-ui** [comment]
on windows

**Comment by djsudduth** [comment]
This issue is now fixed in gkeepapi 0.13.4

**Comment by lucky-d-ui** [comment]
Here I am almost certainly sure that the problem was in multiplayer Chrome. I installed Microsoft Edge and made it the default browser. But it didn't work. I ended up making chrome single-user and it worked.

**Comment by djsudduth** [comment]
All login issues are now in issue #42  (yes, 42, of all things).
