### ISSUE TITLE
ModuleNotFoundError: No module named 'gkeepapi'

### ISSUE THREAD

**Issue by jayb323** [djsudduth/keep-it-markdown#44]
Hey there,

This is an odd one.

I've ran `pip install -r requirements.txt`

But when I go to run `python keep-test.py` I get this error:

`PS C:\keep-it-markdown-0.4.0> python keep-test.py
Traceback (most recent call last):
  File "C:\keep-it-markdown-0.4.0\keep-test.py", line 2, in <module>
    import gkeepapi
ModuleNotFoundError: No module named 'gkeepapi'`

If I run `pip install gkeepapi` I get the requirements are already satisfied so I know it's installed.

`Requirement already satisfied: gkeepapi in c:\users\jasonbinder\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (0.14.2)
Requirement already satisfied: gpsoauth>=1.0.2 in c:\users\jasonbinder\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from gkeepapi) (1.0.2)
Requirement already satisfied: future>=0.16.0 in c:\users\jasonbinder\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from gkeepapi) (0.18.2)
Requirement already satisfied: requests>=2.0.0 in c:\users\jasonbinder\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from gpsoauth>=1.0.2->gkeepapi) (2.28.1)
Requirement already satisfied: pycryptodomex>=3.0 in c:\users\jasonbinder\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from gpsoauth>=1.0.2->gkeepapi) (3.15.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jasonbinder\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests>=2.0.0->gpsoauth>=1.0.2->gkeepapi) (2022.6.15)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\jasonbinder\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests>=2.0.0->gpsoauth>=1.0.2->gkeepapi) (1.26.10)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\jasonbinder\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests>=2.0.0->gpsoauth>=1.0.2->gkeepapi) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jasonbinder\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests>=2.0.0->gpsoauth>=1.0.2->gkeepapi) (3.3)`

Any ideas?

**Comment by jayb323** [comment]
I reinstalled Python and it resolved this issue.

**Comment by djsudduth** [comment]
Thanks for working through the problem!
