### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by fshapps** [djsudduth/keep-it-markdown#45]
Getting the following when attempting to run the script:

```
john@johns-mbp-3 Keep % python ./keep-to-markdown.py -i ./Takeout/Keep/ 
  File "./keep-to-markdown.py", line 14
    cp(f'{path}{file}', os.path.join(notespath, 'resources'))
                     ^
SyntaxError: invalid syntax
```

Unfortunately, I am not a programmer. Some assistance would be appreciated. Thanks!

**Comment by fshapps** [comment]
Figured it out. Needed to specify phython3. Thanks for the awesome tool!

**Comment by ichmoimeyo** [comment]
I believe you reported this in the "wrong" github ... 

https://github.com/erikelisath/keep-to-markdown 

... I think is the one you are using ... anyhow glad you got it solved :)
