### ISSUE TITLE
LoginException('BadAuthentication', None)

### ISSUE THREAD

**Issue by darylf** [djsudduth/keep-it-markdown#56]
I generated an app password, but I can't seem to get it to pass the `keep-test.py` authentication.

Things I've tried which I found in previous Issues:
1. following the link in the error message, but I get a 404
2. `pip3 install --upgrade keyrings.alt` didn't solve anything

`Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: keyrings.alt in /home/username/.local/lib/python3.11/site-packages (4.2.0)
Requirement already satisfied: jaraco.classes in /home/username/.local/lib/python3.11/site-packages (from keyrings.alt) (3.2.3)
Requirement already satisfied: more-itertools in /home/username/.local/lib/python3.11/site-packages (from jaraco.classes->keyrings.alt) (9.0.0)
`

I'm not sure what else I can try to troubleshoot, or what else I can offer to help others understand my issue. Any advice would be welcomed.

**Comment by djsudduth** [comment]
What OS and version are you using? Also, are you using KIM 0.5.0? keep-test.py was deprecated to only providing the token if you needed to copy it.

**Comment by djsudduth** [comment]
PS - I just ran it on Debian 11 using 2FA without any issue.

**Comment by darylf** [comment]
I'm using Fedora 37 with Python 3.11.1

At first I was using a clone of this repo, but I just downloaded the 0.5.0 release zip file and it still isn't working. I see a deprecation warning for imghdr, I'm not sure if that's relevant:

`/home/username/Downloads/keep-it-markdown-0.5.0/kim.py:6: DeprecationWarning: 'imghdr' is deprecated and slated for removal in Python 3.13
  import imghdr`

Stupid question: is a google account username typically an email address? (I'm using my gmail)

**Comment by djsudduth** [comment]
Hmmm.....I've seen this happen on Windows but not on Linux before. Do you have any network blocks / antivirus blocks running?  Or, do you have multiple browsers on Fedora? PS - I haven't tested on v3.11.x of Python yet - but, assuming that isn't the issue.

**Comment by djsudduth** [comment]
Take a look at this comment in the unofficial API -> https://github.com/kiwiz/gkeepapi/issues/81#issuecomment-770389348

I do think there's something device specific that causes this problem - but, I have yet to discover it.

**Comment by djsudduth** [comment]
Tested it on Python v3.11.2 - worked ok

**Comment by djsudduth** [comment]
@darylf - I think using `venv` might be a good thing to try - or, installing a separate fresh version of python and setting your environment to point to it so it's a clean install.

**Comment by jshph** [comment]
I encountered this on my computer too. Set some breakpoints and found that the browser login was required.

See:
https://github.com/kiwiz/gkeepapi/issues/95
https://github.com/kiwiz/gkeepapi/issues/81

I resolved it according to the second link by generating a temp password as instructed! In my case, I am signed into two Google accounts, probably part of the reason why.

**Comment by djsudduth** [comment]
Glad you solved it @jshph!! The 2FA app password seems to work for most.

**Comment by djsudduth** [comment]
@rkallensee very odd! All of my development was on 3.10.x and I tested on 3.11.x. I'm not sure why these blockers appear sometimes. Maybe something about the packages in an existing environment bs a fresh one? Just not sure...

**Comment by djsudduth** [comment]
See #71 for possible fix to the `LoginException('BadAuthentication', None)` error
