### ISSUE TITLE
Username or password is incorrect (LoginException('BadAuthentication'))' 

### ISSUE THREAD

**Issue by Jimmy2times** [djsudduth/keep-it-markdown#58]
Thank u for your good work. Complete noob here, I can't see the password when I type or paste and it showed 'Username or password is incorrect (LoginException('BadAuthentication'))' when I pressed enter. And I Double checked when I typed the app password.

**Comment by djsudduth** [comment]
@Jimmy2times - hi! the pw field is hidden for protection. However, try to copy and paste the app pw (which you need to recreate again) into notepad or word and then hand type it into the pw field very slowly and carefully. Be sure the app pw has no spaces or dashes. It should be 16 digits.

**Comment by Jimmy2times** [comment]
@djsudduth HI, I tried every solution other issues mentioned. It did not work. I can see in my connection logs that there was a request to 'android.clients.google.com:443 ' after I pressed enter. So does that mean the script is running normally? It's probably my google account's faulty setting since I'm the only one encountered this issue, will check again later, thanks again.

**Comment by djsudduth** [comment]
@Jimmy2times - sorry it didn't work for you. Another option for you is to install Virtualbox with a fresh Linux install and shared disk - you can run KIM there (probably too much effort but you could try it).  Or, you could try installing pyenv and see if a new environment with python solves it.

PS - The next version of KIM will have export markdown from the Google Takeout backups from Keep which won't require the API call.
