### ISSUE TITLE
Feature Request: Option to trash Google Keep notes after successful markdown conversion

### ISSUE THREAD

**Issue by quinn-p-mchugh** [djsudduth/keep-it-markdown#60]
Hi @djsudduth,

Thanks for creating this - works great on my end.

**A feature request for your consideration:**

## Summary
I'd love the ability to specify a flag (say, `-t`) that **trashes** any notes in Google Keep that were successfully converted to markdown.

## Current Workflow
My current workflow looks like this:
1. While away from my computer, I capture thoughts/ideas in Google Keep
2. `keep-it-markdown` converts Google Keep notes to markdown and stores files in my Obsidian "Inbox" folder.
    - This process is set to run every 5min via a batch script and Windows Task Scheduler
3. When I'm at my computer, I process the markdown notes in the Obsidian "Inbox" folder and either delete or move elsewhere.

## The Issue
Once I process these converted markdown notes at my computer, I'd like to delete them from the Obsidian "Inbox" folder. However, since these notes are still in my Google Keep, `keep-it-markdown` will resync the notes each time.

Thus, it'd be great if there was the ability to automatically trash any Google Keep notes that were successfully converted to markdown to prevent resyncing.

I took a look at `gkeepapi` and it appears it [does support sending notes to trash](https://github.com/kiwiz/gkeepapi/blob/c8796fa618bfe0317ec1a9e8ad0a859ac24d9519/gkeepapi/node.py#L973-L975).

Looking forward to hearing your thoughts.

**Comment by djsudduth** [comment]
@quinn-p-mchugh very interesting request! I hadn't really considered that option (probably just due to the risk of losing something - especially if a bug is introduced into the code). 

I think the option could easily be added with plenty of warnings. And, I would guess in batch mode you wouldn't want any warning prompts. Let me ponder that for a bit.

**Comment by jdegregorio** [comment]
As an alternative implementation, it might be nice to add an "Imported" tag to keep notes that have been loaded. That way you don't risk losing the data and you keep notes accessible in GKeep until the user explicitly decides to archive/delete. The user could easily filter for a tag and archive all for periodic cleanup.

**Comment by djsudduth** [comment]
@jdegregorio - I want to make sure I'm tracking - by "imported" you mean exported from Keep to markdown and then tag the Keep note, I assume? I'd be a bit worried to add a tag to anyone's existing notes - trying to be a hands-off, read-only export so as not to disrupt notes (except for the new experimental import feature).

**Comment by quinn-p-mchugh** [comment]
> As an alternative implementation, it might be nice to add an "Imported" tag to keep notes that have been loaded. That way you don't risk losing the data and you keep notes accessible in GKeep until the user explicitly decides to archive/delete. The user could easily filter for a tag and archive all for periodic cleanup.

I like this implementation. In summary: it'd be great to have some sort of feature that prevents notes that have been synced in the past from being synced again - whether that's by deleting/archiving the note in Google Keep after successful import into markdown or adding a label is less important for my use case.

**Comment by djsudduth** [comment]
@quinn-p-mchugh my only concern is that tags are a precious commodity in Keep and I've hit the 100 tag limit many times. So I hesitate on that. What about flipping the notes to archive? I know that would mix with other archived notes but those get ignored by kim unless you specifically use the -a flag.

**Comment by quinn-p-mchugh** [comment]
@djsudduth Ah, didn't realize there was a limit on tags/labels! 

Given this, I think adding a flag to archive notes imported to markdown is the way to go.

**Comment by djsudduth** [comment]
Just the research so far - looks totally feasible. I've been trying to focus on the authentication problems some people have first then some feature updates. Appreciate the reach-out and I'll prioritize it.

**Comment by djsudduth** [comment]
@quinn-p-mchugh - feature to move notes to Archive after export added

**Comment by quinn-p-mchugh** [comment]
Wonderful news - thanks for your work, @djsudduth!

A great addition to an already great program.
