### ISSUE TITLE
If a note has no title or body, just a picture, some pictures are named the same and overwritten when using -c option

### ISSUE THREAD

**Issue by github1328** [djsudduth/keep-it-markdown#61]
One of my Keep labels consists of mostly empty notes with just a screenshot or picture. 

Using -c the files get the unique timestamp name since there's no body and no title, but the pictures in the media folder get a 0 added to their filenames. 
Some of them don't have a filename, so they end up being named e.g. 0.jpg. And every next note with no text downloads its picture as 0.jpg, so in the end they all have the latest picture.
It's probably screenshots I took and added from the clipboard, so they never had a filename. In the end I have a 0.jpg, 0.png and a couple of pictures with filename0.jpg in the media folder.

Not using -c the pictures just get the same timestamp name as the note and are all downloaded and work correctly.

Hope this helps, thank you.

Edit:
I assume it has something to do with this code from line 527?

```
 if note.title == '':
                if opts.text_for_title:
                    note.title = re.sub('[' + re.escape(''.join(ILLEGAL_FILE_CHARS)) + ']', '', note.text[0:50])  #.replace(' ',''))
```

I'm very rusty with programming though so I won't try to go down the rabbit hole further.

**Comment by djsudduth** [comment]
Wow! Interesting. Never considered that case. I will take a look! Thanks!

**Comment by djsudduth** [comment]
@github1328 - I've fixed this in the `develop` branch. If using the -c switch then if the note doesn't have a title or text in the body then the date will be used by default. If you want to use this fix just download `kim.py` file in that 'develop` branch. Let me know if that works for you.
