### ISSUE TITLE
AttributeError: module 'urllib3.util.ssl_' has no attribute 'DEFAULT_CIPHERS'

### ISSUE THREAD

**Issue by cyrus01337** [djsudduth/keep-it-markdown#62]
Used Pyenv to create a Python 3.8.16 venv.

Here's the full program output:
```
Welcome to Keep it Markdown or KIM!

Enter your Google account username: 
Enter your Google Password: 


One moment...

Username or password is incorrect (AttributeError("module 'urllib3.util.ssl_' has no attribute 'DEFAULT_CIPHERS'"))
Could not excute KIM
```

Followed the README to create an app password also, but after reading the error, this might not be something I can resolve.

**Comment by djsudduth** [comment]
@cyrus01337 see if you can install / pin an older version of urllib3. What version is installed now by default?

**Comment by cyrus01337** [comment]
Pinning `urllib3` to 1.26.16 changes the error to `LoginException: BadAuthentication`, even when generating a new password.

I will note that I am on Ubuntu 22.04, and my Google account has 2FA enabled, if that is any help.

**Comment by Scrinia** [comment]
I'm on Windows 10 and I have the exact same problem, were you able to find a solution?

**Comment by blumix** [comment]
`pip install urllib3==1.26.1 `

Solved an issue to me

**Comment by Scrinia** [comment]
That worked! Thank you!

**Comment by djsudduth** [comment]
https://github.com/djsudduth/keep-it-markdown/issues/63#issue-1729417724

**Comment by miguelmarcos** [comment]
Many thanks, @blumix. I had this exact problem and your solution worked.

**Comment by cyrus01337** [comment]
I was unable to use this project unfortunately and ended up (gruellingly) migrating manually, however, it seems that there are solutions to this problem that appeared to work for others. Will close, thank you everyone for your time!

**Comment by djsudduth** [comment]
@cyrus01337 sorry it didn't work out. I've added a Docker version that works without you having to install and get it working on your PC (and it works by default as long as your 2FA pw is setup). It's in the new version 0.5.3.
