### ISSUE TITLE
the code is not working with me!

### ISSUE THREAD

**Issue by AbuEssam-Ahmed-helmy** [djsudduth/keep-it-markdown#63]
Hello, thank you for your effort! I followed the whole instructions provided by you. however, after entering my email and password, this error always appears to me. any help will be appreciated
![image](https://github.com/djsudduth/keep-it-markdown/assets/133667606/cb0bde4b-60dc-4a19-8917-67a59ef2dc9d)

**Comment by djsudduth** [comment]
If you can - create a virtual environment or install pyenv to setup a clean install. This error popped up for another user as well and it seems to be related to the urllib3 package.

**Comment by djsudduth** [comment]
@AbuEssam-Ahmed-helmy - I'm closing this since there is another thread with a fix for this
