### ISSUE TITLE
Error on note import: 'charmap' codec can't decode byte 0x81 in position 5455: character maps to <undefined>

### ISSUE THREAD

**Issue by NumberOne925** [djsudduth/keep-it-markdown#64]
Hi,

i want to import md file with notes to google keep or anywhere I can open them. 
When I trying to do this i got this error: Error on note import: 'charmap' codec can't decode byte 0x81 in position 5455: character maps to <undefined>
You knows how to solve this?
i exported my notes from xiaomi cloud using https://github.com/nogiszd/xiaomi-note-exporter

**Comment by djsudduth** [comment]
Yes! This has been fixed in the next version 0.5.1 in the `devel` branch. Choose that branch here and just download the single file `kim.py` to overwrite the current kim file in your version. @NumberOne925

**Comment by NumberOne925** [comment]
wow, it's working, thank you very much!! 
I have another question, it is possible to separate notes by separation mark? e.g. ****

**Comment by djsudduth** [comment]
Glad it's working!! I'm not sure what you mean by the separation of notes. Can you explain more?

**Comment by NumberOne925** [comment]
I have several notes in one note, it looks like:

****
some text
****
some text
****
some text
****
some text

**Comment by djsudduth** [comment]
It would be difficult to add since determining where to place the dividers would be hard to calculate. Your notes might be highly structured making it easier whereas others may not be.
