### ISSUE TITLE
Thank you for this code!!

### ISSUE THREAD

**Issue by dummifiedme** [djsudduth/keep-it-markdown#7]
I had been searching for a tool to smoothen out my workflow, and now with this you have really made it easier for me.
I need to see how well this suits me, but it feels this is it. Since I can use keep anywhere.

I have a few questions/thoughts, if you have some time please look into them :) 

1. What if I keep running with `--all` or same keywords  everytime?
     - Will it duplicate the notes? --> won't be the case, I guess.
     -  Will it populate those notes which are not in the folder? --> Likely
     - Or it stores info about what was imported and when? --> May/May not be :p 
2. How can I automate it to run at some interval?
3. Can there be a way to push the notes as well, in the future? (just curious) 
   - This will enable us a remote view of some notes like daily plan or reminders. Seemless!
4. It could be integrated with the OBSIDIAN PLUGIN? That would be so awesome!

Thanks again!

**Comment by djsudduth** [comment]
Thanks for the comments!!  Do my best to answer you:

What if I keep running with --all or same keywords everytime?
Will it duplicate the notes? --> won't be the case, I guess.
Will it populate those notes which are not in the folder? --> Likely
Or it stores info about what was imported and when? --> May/May not be :p

**A:** If you keep running it to the same output folder, there is no overwriting and notes are duplicated -- if it sees a name collision the names will continue to have date/time appended until the name is too long and the program will error out.  There is no audit trail of what was imported.   Best thing right now is to convert all to a new folder for backup and then create another folder for one-off or keyword export.  I will add an -o overwrite flag in the future.

How can I automate it to run at some interval?

**A:** right now it will always prompt you for the keyword - so no interval (unless you can mimic a user), looks like a feature is needed to pass in a keyword vs prompt


Can there be a way to push the notes as well, in the future? (just curious)
This will enable us a remote view of some notes like daily plan or reminders. Seemless!

**A:** not sure what you mean by push here?

It could be integrated with the OBSIDIAN PLUGIN? That would be so awesome!

**A:** agreed!!  I haven't investigated that yet

Did the login work for you then?

**Comment by dummifiedme** [comment]
Yeah it did.
I dont know how safe it is though.

**Comment by dummifiedme** [comment]
> Did the login work for you then?
Yeah it did. But don't know how safe it is.

Regarding the unclear point. By push I mean, creating a Keep Note from Markdown. There could be some marker or a typical format, that can allow us to put a note inside keep from obsidian.

**Comment by djsudduth** [comment]
Ah, ok - I get what you mean by push. I thought about that but it will be on the backburner for a while.

The library that saves your password is called Keyring and saves it in your local Windows Credential Locker, Mac Keyring or Linux Kwallet or Secret Service.  More info here: https://github.com/jaraco/keyring

If saving your pw locally feels like a security risk for you, just run ->  'python kim.py -r pw'  to remove it from local storage each time you run. You could create a batch/shell script wrapper to do this each time.  I will add a switch to have the option to not save it locally when running.

**Comment by dummifiedme** [comment]
If I am the only person who uses the device, it's a major risk right? 

Also, Can there be a way to import just the notes edited ON or AFTER a certain day? That would be seriously useful if there is some kind of import selection based on dates.

**Comment by djsudduth** [comment]
Windows and Mac Credentials Locker and Keyring are pretty safe - so, the risk seems low to me.  Just to note, your password isn't saved - just the Google Keep token much like how Chrome saves your Google access token. So if it expired or you changed your password it is no longer valid.

I like the export by date idea - on the backlog!!

**Comment by dummifiedme** [comment]
Thanks. I think I will use this plugin for a while then :)

For me its important because its better than manually putting my MD files into my Google Drive in iPad. I haven't yet found a way to have a seamless system to work on both devices. 

In short, THANKS for this tool. Will be looking for the Obsidian Plugin!!

**Comment by dummifiedme** [comment]
Also, if you are looking for more ideas for enhancement, I can suggest a few.
I don't want to seem a lot demanding. They are just suggestions or requests maybe.

1. Tag Based folder --> you can ask for folder path in the config. I don't mean to have many paths, but as subfolder to the main import folder.

2. Date wise import option --> already discussed.

3. As a plugin to Obsidian --> Already discussed.

4. YAML or Content Prefix option --> The basic things could be easily appended to the note like title, created date, last modified date. Useful for most of the people, I guess.

**Comment by djsudduth** [comment]
@dummifiedme - note!  Version 0.3.0 is out!
