### ISSUE TITLE
Is there any workable dockerfile for KIM?

### ISSUE THREAD

**Issue by ooker777** [djsudduth/keep-it-markdown#70]
As the login problem keeps haunting everyone, I guess the simplest solution is to use Docker. Do you have any workable dockerfile for it?

**Comment by djsudduth** [comment]
Unfortunately, not yet. If you scroll to the bottom of the README you'll see it on the list of things to do. 😄

**Comment by ooker777** [comment]
Yeah I did notice it but still wonder why it wasn't applicable now. I thought it demands low effort yet has big impact? Or do you not have time to ensure your dockerfile works for everyone?

---

I went ahead and use this dockerfile:
```
FROM ubuntu:20.04
RUN apt update && apt install -y python-is-python3 python3-pip
COPY . .
RUN cd keep-it-markdown && pip install -r requirements.txt
```

Then it aborts for not being able to wait for user input. I inject my `userid` and `pw` right in the script, then for `kim.py` I have:

`Username or password is incorrect (NoKeyringError('No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.'))`

And for `keep-test.py` I have:
`AttributeError("module 'urllib3.util.ssl_' has no attribute 'DEFAULT_CIPHERS'")
Please start your browser and copy-paste this URL in the address bar: https://accounts.google.com/DisplayUnlockCaptcha - then, try logging in again.`

This improve dockerfile solves these issues:
```
FROM ubuntu:20.04
RUN apt update && apt install -y python-is-python3 python3-pip 
COPY . .
RUN pip install requests==2.23.0 keyrings.alt 
RUN cd keep-it-markdown && pip install -r requirements.txt
CMD python keep-it-markdown/kim.py
```

**Comment by ooker777** [comment]
I see. Yeah I think I solve this, but I'm not sure since I'm also new to Docker. If you don't have time for this I can make a PR as well

**Comment by djsudduth** [comment]
Hey @ooker777 - I could use your help. I was able to create a Dockerfile in issue #72 (Dockerfile steps are there) to get the Keep token successfully. But, I can't seem to get the Keyring/Keystore to run in the Ubuntu Docker image - the `pip install keyring.alt` didn't work in my image (meaning it installed, but would fail with a keyring error when KIM was launched). I've tried installing multiple Keyrings but they've all failed. I think I need a .bashrc setup to launch the service - but not sure yet. At least in issue #72 you can get the token and save it for other OSs.  Any ideas?

**Comment by ooker777** [comment]
Hey, thanks for the getting back. Unfortunately I've done my project for more than a month and my mind now doesn't even recognize the code I wrote :(. To really investigate the problem I need to switch back to the programming context, and [switching costs are high between software development and research thinking](https://notes.andymatuschak.org/zD2oDSCgLEyM4xDhjRLXtuH). I don't remember what happens next after I got the dockerfile, but I can tell that something has happened that I decided to use the gnoteapi directly to save me from headaches.

**Comment by djsudduth** [comment]
No problem. Are you referring to the paid Google Workspace gnoteapi?

**Comment by ooker777** [comment]
no, the [the unofficial one](https://gkeepapi.readthedocs.io/en/latest/index.html "Welcome to gkeepapi’s documentation! — gkeepapi 0.13.6 documentation")

**Comment by djsudduth** [comment]
Ah ok - same one. Thx.
