### ISSUE TITLE
Username or password is incorrect (LoginException('BadAuthentication'))

### ISSUE THREAD

**Issue by DennisDyallo** [djsudduth/keep-it-markdown#71]
Hi guys! First timer user here. Trying to use this on a Windows 10 machine and Python 3.11. 
I'm trying to understand if this app is working at all as of this date today, 1 October. I've read through multiple issues and it seems like login problems are a thing :o 

I created my app password, ran the program, input my username, 
Then I've tried both copy pasting my app password as well as writing it char for char. As the Win terminal doesn't show input, I'm not certain that it's actually taking it in at all. 
**Wondering if I'm doing it correctly and if I should give up.** It's such a shame. I just realized I've lost many Google notes. Reason unknown.  When they were lost? Unknown as well. 
Don't trust Google with your notes apparently.

**Comment by djsudduth** [comment]
Yes, it is still active and used by many. The problem revolves around the python library versions and Google auth. Did you look at the other similar issues with their fixes?

**Comment by djsudduth** [comment]
See issue #62 and see if doing this fixes the problem:

------ Run this command first and then recreate a new Google app password - try it again
"pip install urllib3==1.26.1 

Solved an issue to me"

**Comment by djsudduth** [comment]
Also, try running the script as "Admin" in windows (if you use Linux or Mac try "sudo") - after running the pip command above.

**Comment by djsudduth** [comment]
@DennisDyallo - I had the same problem on a fresh Windows 10 install -  this fixed it for me!
Python version 3.9.1
(run the standard KIM install of "pip install -r requirements" unless you've done it already)
Run these 2 commands:
pip install urllib3==1.25.11
pip install gpsoauth==1.0.2

**Comment by djsudduth** [comment]
Python 3.10.x and 3.11.x made SSL changes that seem to cause issues with Google authentication. @DennisDyallo - see issue #72 on how to solve this.

**Comment by DennisDyallo** [comment]
Thanks, will look into it @djsudduth

**Comment by djsudduth** [comment]
@DennisDyallo - PS, the new version 0.6.0 has the new instructions on how to get the Keep Token to run keep-it-markdown
