### ISSUE TITLE
Language error in keep_query_convert() on Win10

### ISSUE THREAD

**Issue by ndilekli** [djsudduth/keep-it-markdown#82]
Ran the code with the prompt "python kim.py -b --all" to process all the notes but got the message:

Error in keep_query_convert()
Could not excute KIM

after a few notes. Not sure what the nature of the error, but if the code skipped the file causing the issue (while printing the name of the problem file), I could add those manually later.

Also previously I had the error/warning:

'Keep.resume' has been renamed to 'Keep.authenticate'. Please update your code

So I updated the kim.py accordingly (replacing 3 instances of resume with authenticate)

![error](https://github.com/user-attachments/assets/d25dcdf3-b902-4afa-abf8-7a7f4cbfd385)

**Comment by djsudduth** [comment]
@ndilekli Thanks for submitting the issue. Is there any way to narrow down what note might have caused the error? It would be great to see what might have been the problem. 

In the meantime I'll fix the other issues and do the skip over problem notes.

**Comment by ndilekli** [comment]
Strangest thing. I originally tried it on a Win10 machine. Just tried it on a Win11 machine, and everything went smoothly, converted over 600 notes. One other thing I did was to add titles to the top few notes in order to identify which one was causing the problem. But never had the error. Thanks for everything :)

**Comment by ndilekli** [comment]
I don't think so, since both of my Win installations have English and Turkish keyboards installed, but it is not an area I have much expertise on. If there are some lines that can help debug the error, I can check it out as well.

**Comment by arha** [comment]
+1 maybe an issue with i18n. I also have a keep notes with multiple alphabets, tried an export on a win10, same issue. Works first try on a linux, everything was exported right.

**Comment by djsudduth** [comment]
@arha - do you know if the versions of Python were the same on Win10 and Linux?

**Comment by djsudduth** [comment]
I tried some turkish notes and was not able to get it to fail. I'm wondering about the missing titles possibly having something odd within them @ndilekli. Were the titles completely empty in the Win10 case where it failed?

**Comment by djsudduth** [comment]
@ndilekli - I'm going to close this one for now. If it pops up again - maybe you can figure out what caused it and we'll reopen the issue.
